#!/command/with-contenv sh

# Make sure crontab dir exists
mkdir -p /etc/crontabs

# Create/reset the crontab file (truncate to avoid duplicate entries on restart)
: > /etc/crontabs/crontab

# Load the files
for CronFiles in /crons/*
do 
  test -f "$CronFiles" || continue
  echo "Importing ${CronFiles} to crontab" 
  envsubst < ${CronFiles} >> /etc/crontabs/crontab
done

# Add to cron tab
# crontab -u tundra /etc/crontabs/crontab;
crontab /etc/crontabs/crontab;