#!/usr/bin/with-contenv sh

PGID=${PUID:-1000}
UNAME='tundra'
PGID=${PGID:-1000}
GNAME='tundra'

if [ $PGID -ne 1000 ]; then
  groupmod -o -g "$PGID" $GNAME
fi
if [ $PUID -ne 1000 ]; then
  usermod -o -u "$PUID" $UNAME
fi

# chown tundra:tundra -R /app
# setgroup /app
setgroup /scripts/bin

# ensure all scripts inside /scripts/bin are executable
chmod +x /scripts/bin/*
