#!/command/with-contenv sh

PUID=${PUID:-1000}
PGID=${PGID:-1000}
UNAME='tundra'
GNAME='tundra'

if [ $PGID -ne 1000 ]; then
  groupmod -o -g "$PGID" $GNAME
fi
if [ $PUID -ne 1000 ]; then
  usermod -o -u "$PUID" $UNAME
fi

# chown tundra:tundra -R /app
# setgroup /app
setgroup /scripts

# ensure all scripts inside /scripts are executable
chmod +x /scripts/*
