#!/bin/sh
# chown -R tundra:tundra "$@" || printf "**** Could not set permission for $@. ****\n**** Application may not work as intended ****"
if find "$@" ! -user tundra -o ! -group tundra | grep -q .; then
  chown -R tundra:tundra "$@" || printf "**** Could not set permission for $@. ****\n**** Application may not work as intended ****"
fi