#!/usr/bin/with-contenv sh

TZ=${TZ:-'UTC'}

# Remove existing file if exists
if [ -f /etc/timezone ]; then
  rm -rf /etc/timezone /etc/localtime
fi

# Set timezone
if [ ! -f /usr/share/zoneinfo/${TZ} ]; then
  echo "Could not find time zone ${TZ}."
  kill -s TERM 1
fi

# printf "Setting timezone to ${TZ}...."
cp /usr/share/zoneinfo/${TZ} /etc/localtime
echo $TZ >/etc/timezone
# printf "Done.\n"
