name: Build and Test Docker Image

on:
  push:
    paths-ignore:
      - .dockerignore
      - .gitignore
      - .github/ISSUE_TEMPLATE/*
      - .github/PULL_REQUEST_TEMPLATE*
      - ./README.md
      - ./LICENSE
    # Ignore CI if commit message contains '[skip ci]' (e.g., from update-readme chore)
    # This is a GitHub Actions convention, not a YAML field, so we use a job-level if below
  pull_request:
    branches: [ main ]
  schedule:
    - 
      cron: '0 0 * * 0'

jobs:

  setup:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    outputs:
      alpine-branches: ${{ steps.alpine-versions.outputs.alpine-branches }}
      latest-alpine-branch: ${{ steps.alpine-versions.outputs.latest-alpine-branch }}
      # s6-versions: ${{ steps.s6-versions.outputs.s6-versions }}
      latest-s6-version: ${{ steps.s6-versions.outputs.latest-s6-version }}

    steps:
      - 
        name: Get Alpine Versions
        id: alpine-versions
        run: |
          LATEST_VERSION=$(curl -s https://cz.alpinelinux.org/alpine/latest-stable/releases/x86_64/latest-releases.yaml | awk '/branch:/ {print $2; exit}')
          ALPINE_BRANCHES="edge "
          LIMIT=3
          ALL_BRANCHES=$(curl -s https://cz.alpinelinux.org/alpine/ | grep -oP '(?<=v)[^/]+(?=/")' | sort -V | tail -n 6 | tac)
          for BRANCH in $ALL_BRANCHES
          do
            if curl --output /dev/null --silent --head --fail "https://cz.alpinelinux.org/alpine/v${BRANCH}/releases/";
            then
              ALPINE_BRANCHES+="v${BRANCH} "
              LIMIT=$((LIMIT-1))
            fi
            if [ $LIMIT -le 0 ]; then
              break
            fi
          done
          ALPINE_BRANCHES=$(echo $ALPINE_BRANCHES | tr ' ' '\n' | jq -Rcn '[inputs] | sort | reverse')
          echo "alpine-branches=${ALPINE_BRANCHES}" >> "$GITHUB_OUTPUT"
          echo "latest-alpine-branch=${LATEST_VERSION}" >> "$GITHUB_OUTPUT"
          
      - 
        name: Get S6 Versions
        id: s6-versions
        run: |
          S6_VERSIONS=""
          # Fetch the latest 3 minor versions
          MINOR_VERSIONS=$(curl -s https://api.github.com/repos/just-containers/s6-overlay/releases | jq -r '.[].tag_name' | grep -oP '^v[0-9]+\.[0-9]+\.[0-9]+' | sort -Vu | tail -n 3)
          for VERSION in $MINOR_VERSIONS
          do
            # Fetch the latest patch version for each minor version
            PATCH_VERSION=$(curl -s https://api.github.com/repos/just-containers/s6-overlay/releases | jq -r '.[].tag_name' | grep "^${VERSION}" | sort -V | tail -n 1)
            S6_VERSIONS+="${PATCH_VERSION#v} "
          done
          S6_VERSIONS=$(echo $S6_VERSIONS | tr ' ' '\n' | jq -Rcn '[inputs] | sort | reverse')
          LATEST_VERSION=$(echo $S6_VERSIONS | tr ' ' '\n' | jq -r '.[0]')
          # echo "s6-versions=${S6_VERSIONS}" >> "$GITHUB_OUTPUT"
          echo "latest-s6-version=${LATEST_VERSION}" >> "$GITHUB_OUTPUT"
      
  build:
    needs: setup
    runs-on: ubuntu-latest
      
    strategy:
      fail-fast: true
      matrix:
        alpine-branch: ${{ fromJson(needs.setup.outputs.alpine-branches) }}
        # s6-version: ${{ fromJson(needs.setup.outputs.s6-versions) }}
    
    env:
      ALPINE_VERSION: ''
      TEST_TAG: alpine-s6
    
    steps:
    - 
      uses: actions/checkout@v4
    
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    -
      name: Get the ALPINE VERSION
      run: |
        echo "ALPINE_VERSION=$(curl -s https://cz.alpinelinux.org/alpine/${{ matrix.alpine-branch }}/releases/x86_64/latest-releases.yaml | awk '/version:/ {print $2; exit}')" >> $GITHUB_ENV
    
    - 
      name: Extract Docker Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        flavor: |
          latest=false
        images: |
          name=${{ github.repository }},enable=true
          name=ghcr.io/${{ github.repository }},enable=true
        labels: |
          org.opencontainers.image.source=${{ github.repositoryUrl }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.created=${{ github.event.repository.pushed_at }}
          org.opencontainers.image.authors=${{ github.actor }}
          org.opencontainers.image.branch=${{ github.ref_name }}
          org.opencontainers.image.vendor=Tundrasoft
          org.opencontainers.image.licenses=MIT
          org.opencontainers.image.documentation=${{ github.repositoryUrl }}/blob/main/README.md
          org.opencontainers.image.description=Alpine Linux with S6 Overlay
          org.opencontainers.image.title=Alpine Linux with S6 Overlay
        tags: |
          type=raw,prefix=,value=latest,enable=${{ ( matrix.alpine-branch == needs.setup.outputs.latest-alpine-branch && matrix.alpine-branch != 'edge' && github.ref_name == github.event.repository.default_branch) }}
          # Version tags for non-edge releases
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ env.ALPINE_VERSION }},enable=${{ matrix.alpine-branch != 'edge' && github.ref_name == github.event.repository.default_branch }}
          type=semver,pattern={{major}}.{{minor}},value=${{ env.ALPINE_VERSION }},enable=${{ matrix.alpine-branch != 'edge' && github.ref_name == github.event.repository.default_branch }}
          type=semver,pattern={{major}},value=${{ env.ALPINE_VERSION }},enable=${{ matrix.alpine-branch != 'edge' && matrix.alpine-branch == needs.setup.outputs.latest-alpine-branch && github.ref_name == github.event.repository.default_branch }}
          # Edge version tags
          type=raw,value=${{ env.ALPINE_VERSION }},enable=${{ matrix.alpine-branch == 'edge' && github.ref_name == github.event.repository.default_branch }}
          type=raw,value=edge,enable=${{ matrix.alpine-branch == 'edge' && github.ref_name == github.event.repository.default_branch }}
          # Branch-prefixed tags for non-default branches
          type=semver,prefix=${{ format('{0}-', github.ref_name)}},pattern={{major}}.{{minor}}.{{patch}},value=${{ env.ALPINE_VERSION }},enable=${{ matrix.alpine-branch != 'edge' && github.ref_name != github.event.repository.default_branch }}
          type=raw,prefix=${{ format('{0}-', github.ref_name)}},value=${{ env.ALPINE_VERSION }},enable=${{ matrix.alpine-branch == 'edge' && github.ref_name != github.event.repository.default_branch }}

    - 
      name: Build Test Image
      id: build-image
      uses: docker/build-push-action@v6
      with:
        context: .
        load: true
        tags: ${{ env.TEST_TAG }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          ALPINE_BRANCH=${{ matrix.alpine-branch }}
          ALPINE_VERSION=${{ env.ALPINE_VERSION }}
          S6_VERSION=${{ needs.setup.outputs.latest-s6-version }}
    
    -
      name: Test Image
      run: |
        # Check Alpine version
        output=$(docker run --rm ${{ env.TEST_TAG}} /bin/sh -c "cat /etc/alpine-release | grep -q ${{ env.ALPINE_VERSION }} && echo 'OK' || echo 'KO'")
        if [ "$output" == "OK" ]; then
          echo "Alpine version test passed"
        else
          echo "Alpine version test failed"
          exit 1
        fi
        # Check s6-overlay is present
        docker run --rm ${{ env.TEST_TAG}} /bin/sh -c "[ -x /init ] && echo 's6-overlay present' || (echo 's6-overlay missing' && exit 1)"
        # Check cron is installed and can start
        docker run --rm ${{ env.TEST_TAG}} /bin/sh -c "crond --help && echo 'cron present' || (echo 'cron missing' && exit 1)"
        # Check tundra user exists
        docker run --rm ${{ env.TEST_TAG}} /bin/sh -c "id tundra && echo 'tundra user exists' || (echo 'tundra user missing' && exit 1)"
        # Check timezone can be set
        docker run --rm -e TZ=Asia/Kolkata ${{ env.TEST_TAG}} /bin/sh -c "cat /etc/timezone | grep -q 'Asia/Kolkata' && echo 'Timezone OK' || (echo 'Timezone FAIL' && exit 1)"
        # Check /crons is writable by tundra
        docker run --rm ${{ env.TEST_TAG}} /bin/sh -c "touch /crons/testfile && echo 'crons writable' || (echo 'crons not writable' && exit 1)"
        echo "All tests passed."
    
    -
      name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    -
      name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GIT_HUB_TOKEN }}
    
    - 
      name: Build and Push
      id: build-push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        #,linux/arm/v7
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        provenance: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          ALPINE_BRANCH=${{ matrix.alpine-branch }}
          ALPINE_VERSION=${{ env.ALPINE_VERSION }}
          S6_VERSION=${{ needs.setup.outputs.latest-s6-version }}
  
  # Lets do a few chores
  update-readme:
    needs: [setup, build]
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install Python dependencies
        run: |
          pip install -r .github/scripts/requirements.txt
      
      - name: Update README with new tags
        run: |
          # Use the Alpine branches that were actually built
          ALPINE_BRANCHES='${{ needs.setup.outputs.alpine-branches }}'
          echo "Processing Alpine branches that were built: $ALPINE_BRANCHES"
          
          # Convert JSON array to bash array
          BRANCHES=$(echo "$ALPINE_BRANCHES" | jq -r '.[]')
          
          # Process each branch that was built
          for BRANCH in $BRANCHES; do
            if [ "$BRANCH" != "edge" ]; then
              # Get the version for this branch (same as what was used in build)
              VERSION=$(curl -s "https://cz.alpinelinux.org/alpine/${BRANCH}/releases/x86_64/latest-releases.yaml" | awk '/version:/ {print $2; exit}')
              if [ -n "$VERSION" ]; then
                echo "Updating README with successfully built version: $VERSION"
                python .github/scripts/update_readme_tags.py README.md "$VERSION" "${{ github.repository }}"
              else
                echo "Warning: Could not get version for branch $BRANCH"
              fi
            else
              echo "Skipping edge branch for README update"
            fi
          done
      
      - name: Generate Docker Hub README
        run: |
          echo "Generating DOCKER.md for Docker Hub..."
          python .github/scripts/generate_docker_readme.py \
            README.md \
            DOCKER.md \
            '${{ needs.setup.outputs.alpine-branches }}' \
            '${{ github.repository }}' \
            '${{ github.repository }}' \
            '${{ needs.setup.outputs.latest-s6-version }}' \
            'description:DESCRIPTION-START,DESCRIPTION-END;env-vars:ENV-VARS-START,ENV-VARS-END;build-args:BUILD-ARGS-START,BUILD-ARGS-END'
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md DOCKER.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update README.md and DOCKER.md with latest tags [skip ci]"
            git push origin ${{ github.ref_name }}
          fi
  
  chore:
    needs: build
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        continue-on-error: true
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          readme-filepath: ./DOCKER.md

