name: Build and Test Docker Image

on:
  push:
    paths-ignore:
      - .dockerignore
      - .gitignore
      - .github/ISSUE_TEMPLATE/*
      - .github/PULL_REQUEST_TEMPLATE*
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      alpine-versions: ${{ steps.get-versions.outputs.alpine-versions }}
      s6-versions: ${{ steps.get-versions.outputs.s6-versions }}
    steps:
    - id: get-versions
      run: |
        ALPINE_VERSIONS=$(curl -s https://cz.alpinelinux.org/alpine/ | grep -oP '(?<=v)[^/]+(?=/")' | sort -V | tail -n 5 | tac | jq -Rcn '[inputs]')
        S6_VERSIONS=$(curl -s https://api.github.com/repos/just-containers/s6-overlay/releases | jq -r '.[].tag_name' | sort -V | tail -3 | jq -R . | jq -s .)
        echo "::set-output name=alpine-versions::${ALPINE_VERSIONS}"
        echo "::set-output name=s6-versions::${S6_VERSIONS}"

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        alpine-version: ${{ fromJson(needs.setup.outputs.alpine-versions) }}
        s6-version: ${{ fromJson(needs.setup.outputs.s6-versions) }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    -
      name: Login to DockerHub
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name != 'pull_request'
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Login to GHCR
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GIT_HUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ github.repository }}2:alpine-${{ matrix.alpine-version }}-s6-${{ matrix.s6-version }}
          ghcr.io/${{ github.repository }}2:alpine-${{ matrix.alpine-version }}-s6-${{ matrix.s6-version }}
          ${{ (matrix.alpine-version == fromJson(needs.setup.outputs.alpine-versions)[0] && matrix.s6-version == fromJson(needs.setup.outputs.s6-versions)[0]) && '${{ github.repository }}2:latest, ghcr.io/${{ github.repository }}/alpine2:latest' }}
        build-args: 
          ALPINE_VERSION=${{ matrix.alpine_version }}
          S6_VERSION=${{ matrix.s6-version }}

    - name: Test
      run: |
        docker pull ${{ github.repository }}2:alpine-${{ matrix.alpine-version }}-s6-${{ matrix.s6-version }}
        output=$(docker run --rm ${{ github.repository }}2:alpine-${{ matrix.alpine-version }}-s6-${{ matrix.s6-version }} /bin/sh -c "cat /etc/alpine-release | grep -q ${{ matrix.alpine-version }} && echo 'OK' || echo 'KO'")
          if [ "$output" == "OK" ]; then
            echo "Test Passed"
          else
            echo "Test Failed"
            exit 1
          fi